#!/bin/bash
# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -n "${ANDROID_BUILD_TOP}" ]; then
    ANDROID_SOURCE_TREE="${ANDROID_BUILD_TOP}"
else
    ANDROID_SOURCE_TREE="$PWD/../../../../../../"
fi

OUT="${ANDROID_SOURCE_TREE}out/soong/.intermediates/"

CLASSPATH=""
CLASSPATH+="${ANDROID_SOURCE_TREE}external/kotlinc/lib/kotlin-stdlib.jar"
CLASSPATH+=":${ANDROID_SOURCE_TREE}prebuilts/sdk/33/system-server/android.jar"
CLASSPATH+=":${OUT}external/kotlinx.coroutines/kotlinx-coroutines-core/android_common/turbine-combined/kotlinx-coroutines-core.jar"
CLASSPATH+=":${OUT}packages/modules/Bluetooth/framework/framework-bluetooth-pre-jarjar/android_common/turbine-combined/framework-bluetooth-pre-jarjar.jar"
CLASSPATH+=":${OUT}packages/modules/Bluetooth/pandora/interfaces/pandora-grpc-java/android_common/turbine-combined/pandora-grpc-java.jar"
CLASSPATH+=":${OUT}packages/modules/Bluetooth/pandora/interfaces/pandora-proto-java/android_common/turbine-combined/pandora-proto-java.jar"
CLASSPATH+=":${OUT}prebuilts/misc/common/androidx-test/androidx.test.core/android_common/combined/androidx.test.core.jar"
CLASSPATH+=":${OUT}external/protobuf/libprotobuf-java-micro/android_common/turbine-combined/libprotobuf-java-micro.jar"

echo "$CLASSPATH"
