#!/bin/bash


ROOT="$PWD/../../../../"
CLASSPATH=""
CLASSPATH+="$ROOT/external/kotlinc/lib/kotlin-stdlib.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/frameworks/base/api/android_system_server_stubs_current/android_common/turbine-combined/android_system_server_stubs_current.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/appcompat/appcompat/1.7.0-alpha04/androidx.appcompat_appcompat/android_common_apex33/turbine-combined/androidx.appcompat_appcompat.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/framework/framework-bluetooth-pre-jarjar/android_common/turbine-combined/framework-bluetooth-pre-jarjar.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/libcore/core-lambda-stubs/android_common/turbine-combined/core-lambda-stubs.jar"

CLASSPATH+=":$ROOT/out/soong/.intermediates/frameworks/libs/modules-utils/java/framework-annotations-lib/android_common/turbine-combined/framework-annotations-lib.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/ConfigInfrastructure/framework/framework-configinfrastructure.stubs.module_lib/android_common/turbine-combined/framework-configinfrastructure.stubs.module_lib.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/StatsD/framework/framework-statsd.stubs.module_lib/android_common/turbine-combined/framework-statsd.stubs.module_lib.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/service/change-ids/service-bluetooth.change-ids/android_common/turbine-combined/service-bluetooth.change-ids.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/framework/framework-bluetooth.impl/android_common/turbine-jarjar/framework-bluetooth.impl.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/prebuilts/sdk/current/androidx/m2repository/androidx/annotation/annotation-jvm/1.8.0-alpha01/androidx.annotation_annotation/android_common_apex33/turbine-combined/androidx.annotation_annotation.jar"

CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/service/bluetooth-manager-service-proto-java-gen/android_common_apex33/turbine-combined/bluetooth-manager-service-proto-java-gen.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/service/bluetooth-nano-protos/android_common_apex33/turbine-combined/bluetooth-nano-protos.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/android/app/bluetooth-proto-enums-java-gen/android_common_apex33/turbine-combined/bluetooth-proto-enums-java-gen.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/packages/modules/Bluetooth/flags/bluetooth_flags_java_lib/android_common_apex33/turbine-combined/bluetooth_flags_java_lib.jar"
CLASSPATH+=":$ROOT/out/soong/.intermediates/frameworks/libs/modules-utils/java/com/android/modules/utils/modules-utils-shell-command-handler/android_common_apex33/turbine-combined/modules-utils-shell-command-handler.jar"

echo "$CLASSPATH"
