#
#  Copyright 2021 Google, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import("//bt/system/gd/packet/parser/packetgen.gni")
import("//common-mk/flatbuffer.gni")

config("gd_defaults") {
  cflags_cc = [
    "-DGOOGLE_PROTOBUF_NO_RTTI",
    "-Wno-unused-result",
    "-Wno-tautological-overlap-compare",
  ]

  defines = [ "TARGET_FLOSS" ]

  libs = [
    "ssl",
    "crypto",
  ]

  include_dirs = [ "//bt/system/gd" ]
  configs = [
    "//bt/system:target_defaults",
    "//bt/system/log:log_defaults",
  ]
}

config("rust_defaults") {
  # Empty for now
}

group("gd_default_deps") {
  deps = [
    "//bt/system:libbt-platform-protos-lite",
    "//bt/system/pdl:BluetoothGeneratedPackets_h",
  ]
}

static_library("libbluetooth_gd") {
  sources = [ "module.cc" ]

  include_dirs = [ "." ]
  configs += [ ":gd_defaults" ]
  deps = [
    "//bt/system/gd/common:BluetoothCommonSources",
    "//bt/system/gd/hal:BluetoothHalSources",
    "//bt/system/gd/hal:BluetoothHalSources_hci_host",
    "//bt/system/gd/hal:BluetoothHalSources_ranging_host",
    "//bt/system/gd/hal:BluetoothHalSources_socket_host",
    "//bt/system/gd/metrics:BluetoothMetricsSources",
    "//bt/system/gd/rust/topshim:libbluetooth_topshim",
    "//bt/system/gd/storage:BluetoothStorageSources",
    "//bt/system/gd/sysprops:BluetoothSyspropsSources",
    "//bt/system/pdl:BluetoothGeneratedPackets_h",
  ]
}
